#ifndef CNBICVSA_FLAGS_HPP
#define CNBICVSA_FLAGS_HPP


/*** Color feedback default values ***/
#define CNBICVSA_COLORFEEDBACK_RING_RADIUS		0.18f
#define CNBICVSA_COLORFEEDBACK_RING_THICK		0.03f

#define CNBICVSA_COLORFEEDBACK_FILL_RADIUS		0.18f
#define CNBICVSA_COLORFEEDBACK_FEEDBACK_RADIUS	0.18f


/*** Target gallery default values ***/
#define CNBICVSA_TARGETGALLERY_X		0.0f
#define CNBICVSA_TARGETGALLERY_Y		0.0f
#define CNBICVSA_TARGETGALLERY_WIDTH	0.5f
#define CNBICVSA_TARGETGALLERY_HEIGHT	0.5f

#endif
